
// link_syms_vals.h

#ifndef BJ_LINK_SYMS_VALS_H
#define BJ_LINK_SYMS_VALS_H

#ifdef BJ_IS_EPH_CODE

extern bj_addr_t LD_EXTERNAL_RAM_SIZE;
extern bj_addr_t LD_EXTERNAL_CODE_SIZE;
extern bj_addr_t LD_EXTERNAL_LOAD_SIZE;
extern bj_addr_t LD_EXTERNAL_DATA_SIZE;
extern bj_addr_t LD_EXTERNAL_ALLOC_SIZE;
extern bj_addr_t LD_EXTERNAL_RAM_ORIG;
extern bj_addr_t LD_EXTERNAL_CODE_ORIG;
extern bj_addr_t LD_EXTERNAL_LOAD_ORIG;
extern bj_addr_t LD_EXTERNAL_DATA_ORIG;
extern bj_addr_t LD_EXTERNAL_ALLOC_ORIG;

extern bj_addr_t LD_CORE_MODULE_ORIG;
extern bj_addr_t LD_CORE_MODULE_SIZE;

#define BJK_LNK_SCRPT_SYM_VAL(xx) ((bj_addr_t)(&xx))

#define BJ_VAL_EXTERNAL_RAM_SIZE 	BJK_LNK_SCRPT_SYM_VAL(LD_EXTERNAL_RAM_SIZE)
#define BJ_VAL_EXTERNAL_CODE_SIZE 	BJK_LNK_SCRPT_SYM_VAL(LD_EXTERNAL_CODE_SIZE)
#define BJ_VAL_EXTERNAL_LOAD_SIZE 	BJK_LNK_SCRPT_SYM_VAL(LD_EXTERNAL_LOAD_SIZE)
#define BJ_VAL_EXTERNAL_DATA_SIZE 	BJK_LNK_SCRPT_SYM_VAL(LD_EXTERNAL_DATA_SIZE)
#define BJ_VAL_EXTERNAL_ALLOC_SIZE 	BJK_LNK_SCRPT_SYM_VAL(LD_EXTERNAL_ALLOC_SIZE)
#define BJ_VAL_EXTERNAL_RAM_ORIG 	BJK_LNK_SCRPT_SYM_VAL(LD_EXTERNAL_RAM_ORIG)
#define BJ_VAL_EXTERNAL_CODE_ORIG 	BJK_LNK_SCRPT_SYM_VAL(LD_EXTERNAL_CODE_ORIG)
#define BJ_VAL_EXTERNAL_LOAD_ORIG 	BJK_LNK_SCRPT_SYM_VAL(LD_EXTERNAL_LOAD_ORIG)
#define BJ_VAL_EXTERNAL_DATA_ORIG 	BJK_LNK_SCRPT_SYM_VAL(LD_EXTERNAL_DATA_ORIG)
#define BJ_VAL_EXTERNAL_ALLOC_ORIG 	BJK_LNK_SCRPT_SYM_VAL(LD_EXTERNAL_ALLOC_ORIG)

#define BJ_VAL_CORE_MODULE_ORIG 	BJK_LNK_SCRPT_SYM_VAL(LD_CORE_MODULE_ORIG)
#define BJ_VAL_CORE_MODULE_SIZE 	BJK_LNK_SCRPT_SYM_VAL(LD_CORE_MODULE_SIZE)

#endif

#endif // BJ_LINK_SYMS_VALS_H

